{
    "cmd": "register",
    "username": "Vasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_PupkinVasya_Pupkin",
    "password": "123456"
}